#!/bin/bash

# A script to display a series of numbers using until.

counter=1
until [[ "$counter" -gt 10 ]]; do
    echo "The counter is at: $counter"
    counter=$((counter + 1))
done
echo "The count has finished."


# Starting from 20 until it reaches 0
value=20
until [[ "$value" -eq 0 ]]; do
    echo "The value is at: $value"
    value=$((value - 1))
done
echo "The value has reached $value"
