#!/bin/bash

# A script that will determine if a number is even
number=5

# Compound command -> Arithmetic truth tests
# 0 or 1 
if [ $((number % 2)) -eq 0 ];
then
   echo "The number $number is even!";
else 
   echo "The number $number is odd!"
fi
